// @ts-check

/**
 * 애플리케이션 상태를 위한 액션 유형.
 * @enum {string}
 */
export const ACTIONS = {
  SET_MAP: "SET_MAP",
  SET_LOADING_STATE: "SET_LOADING_STATE",
  UPDATE_FILTER: "UPDATE_FILTER",
  ADD_MARKER: "ADD_MARKER",
  REMOVE_MARKER: "REMOVE_MARKER",
  SET_USER_PREFERENCE: "SET_USER_PREFERENCE",
  UPDATE_COMPLETED_LIST: "UPDATE_COMPLETED_LIST",
  UPDATE_FAVORITES: "UPDATE_FAVORITES",
  OPEN_LIGHTBOX: "OPEN_LIGHTBOX",
  CLOSE_LIGHTBOX: "CLOSE_LIGHTBOX",
  SET_DEV_MODE: "SET_DEV_MODE",
};
